export const TICK = 'TICK';
export const APPLY_OFFLINE = 'APPLY_OFFLINE';
export const SACRIFICE = 'SACRIFICE';
export const SACRIFICE_MEMBER = 'SACRIFICE_MEMBER';
export const BUY_UPGRADE = 'BUY_UPGRADE';
export const RECRUIT_MEMBER = 'RECRUIT_MEMBER';
export const START_MISSION = 'START_MISSION';
export const RESOLVE_MISSIONS = 'RESOLVE_MISSIONS';
export const PRESTIGE = 'PRESTIGE';
export const REVEAL_BOON = 'REVEAL_BOON';
export const BUY_BOON = 'BUY_BOON';
export const UNLOCK_LORE = 'UNLOCK_LORE';
export const LOAD_GAME = 'LOAD_GAME';
export const RESET = 'RESET';
export const STAMP_SAVED = 'STAMP_SAVED';
export const AUTO_FIRE = 'AUTO_FIRE';

export const tick = (dtMs) => ({ type: TICK, dtMs });
export const applyOffline = (dtMs) => ({ type: APPLY_OFFLINE, dtMs });
export const sacrifice = () => ({ type: SACRIFICE });
export const sacrificeMember = (id) => ({ type: SACRIFICE_MEMBER, id });
export const buyUpgrade = (id) => ({ type: BUY_UPGRADE, id });
export const recruitMember = (id) => ({ type: RECRUIT_MEMBER, id });
export const startMission = (id) => ({ type: START_MISSION, id });
export const resolveMissions = (now = Date.now()) => ({ type: RESOLVE_MISSIONS, now });
export const prestige = () => ({ type: PRESTIGE });
export const revealBoon = (forcedId = null) => ({ type: REVEAL_BOON, forcedId });
export const buyBoon = (id) => ({ type: BUY_BOON, id });
export const unlockLore = (id) => ({ type: UNLOCK_LORE, id });
export const loadGame = (state) => ({ type: LOAD_GAME, state });
export const reset = () => ({ type: RESET });
export const stampSaved = (now) => ({ type: STAMP_SAVED, now });
export const autoFire = (memberId, payload) => ({ type: AUTO_FIRE, memberId, payload });
